#file: noinspection SpellCheckingInspection,SpellCheckingInspection
# noinspection YAMLSchemaValidation
name: ${project.name}
version: ${project.version}
main: net.blackofworld.SneakyBastard.Start
load: STARTUP
author: BlackOfWorld <3
description: SneakyBastard, a good angel.
api-version: 1.17
website: https://blackofworld.fun