#file: noinspection SpellCheckingInspection,SpellCheckingInspection
# noinspection YAMLSchemaValidation
name: $name
version: $version
main: net.blackofworld.SneakyBastard.Start
load: STARTUP
authors:
  - BlackOfWorld <3
description: SneakyBastard, a good angel.
api-version: $apiVersion
website: https://blackofworld.fun